- id: 'desk_light_sunset'
  alias: desk light on sunset
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  action:
    service: switch.turn_on
    entity_id: switch.desk_lamp

- id: 'desk_light_bedtime'
  alias: desk light off bedtime
  description: ''
  trigger:
  - platform: time
    at: "22:15:00"
  action:
    service: switch.turn_off
    entity_id: switch.desk_lamp

- id: lava_lamp_on_lounge_work_nights
  alias: on lava lamp work nights
  description: ''
  trigger:
  - event: sunset
    offset: +00:30:00
    platform: sun
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  action:
    service: switch.turn_on
    entity_id: switch.lava_lamp

- id: lava_lamp_off_work_nights
  alias: off lava lamp work nights
  description: ''
  trigger:
  - platform: time
    at: "22:15:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  action:
    service: switch.turn_off
    entity_id: switch.lava_lamp

- id: first_hue_light_automation
  alias: first_hue_light_automation
  description: ''
  trigger:
  - platform: time
    at: "19:54:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - thu
      - fri
  action:
    service: light.turn_off
    entity_id: light.landing

- id: xmas_lights_on_schooldays
  alias: on xmas lights schooldays
  description: ''
  trigger:
  - platform: time
    at: "15:00:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_on
    entity_id: switch.xmas_lights
    
- id: xmas_lights_on_weekend
  alias: on xmas lights weekend
  description: ''
  trigger:
  - event: sunset
    platform: sun
    offset: '+00:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: switch.turn_on
    entity_id: switch.xmas_lights
    
- id: xmas_lights_off
  alias: off xmas lights
  description: ''
  trigger:
  - platform: time
    at: "21:45:00"
  action:
    service: switch.turn_off
    entity_id: switch.xmas_lights
