
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
  platform: rpi_rf
  gpio: 17
  switches:
    lounge_lava_lamp:
      code_on: !secret red_lava_lamp_switch_on
      code_off: !secret red_lava_lamp_switch_off
      pulselength: 200
      signal_repetitions: 20
    monkey_lava_lamp:
      code_on: !secret blue_lava_lamp_switch_on
      code_off: !secret blue_lava_lamp_switch_off
      pulselength: 200
      signal_repetitions: 20
    xmas_lights:
      code_on: !secret xmas_lights_switch_on
      code_off: !secret xmas_lights_switch_off
      pulselength: 200
      signal_repetitions: 30
    fish_tank:
      code_on: !secret fish_tank_switch_on
      code_off: !secret fish_tank_switch_off
      pulselength: 200
      signal_repetitions: 30
      
binary_sensor:
  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]

device_tracker:
  - platform: bluetooth_le_tracker
    interval_seconds: 45 # changed from default of 12
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
  - platform: bluetooth_tracker
    interval_seconds: 45 # changed from default of 12
    consider_home: 180
    new_device_defaults:
      track_new_devices: false
  - platform: nmap_tracker
    hosts: 192.168.1.0/24
    home_interval: 10
    exclude:
      - 192.168.1.1
      - 192.168.1.2
      - 192.168.1.3
      - 192.168.1.6
