
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
   base_url: !secret duckdns
   ssl_certificate: /ssl/fullchain.pem
   ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


switch:
  platform: rpi_rf
  gpio: 17
  switches:
    lava_lamp:
      code_on: !secret lava_lamp_switch_on
      code_off: !secret lava_lamp_switch_off
      pulselength: 200
      signal_repetitions: 20
    desk_lamp:
      code_on: !secret desk_lamp_switch_on
      code_off: !secret desk_lamp_switch_off
      pulselength: 200
      signal_repetitions: 20
    porch_snowman:
      code_on: !secret snowman_switch_on
      code_off: !secret snowman_switch_off
      pulselength: 200
      signal_repetitions: 20
      
binary_sensor:
  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun]
