- id: xmas_lights_on_schooldays_am
  alias: on xmas lights schooldays am
  description: ''
  trigger:
  - platform: time
    at: "06:45:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_on
    entity_id: switch.xmas_lights

- id: xmas_lights_on_schooldays_pm
  alias: on xmas lights schooldays pm
  description: ''
  trigger:
  - platform: time
    at: "15:00:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_on
    entity_id: switch.xmas_lights
    
- id: xmas_lights_on_weekend
  alias: on xmas lights weekend
  description: ''
  trigger:
  - event: sunset
    platform: sun
    offset: '+00:00:00'
  condition:
    condition: time
    weekday:
      - sat
      - sun
  action:
    service: switch.turn_on
    entity_id: switch.xmas_lights
    
- id: xmas_lights_off_pm
  alias: off xmas lights pm
  description: ''
  trigger:
  - platform: time
    at: "21:45:00"
  action:
    service: switch.turn_off
    entity_id: switch.xmas_lights

- id: xmas_lights_off_schooldays_am
  alias: off xmas lights schooldays am
  description: ''
  trigger:
  - platform: time
    at: "09:15:00"
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: switch.turn_off
    entity_id: switch.xmas_lights
